name: stoseq
channels:
 - conda-forge
 - bioconda
dependencies:
  - trimmomatic
  - star
  - fastq-scan
  - pigz
  - pip
  - poetry =1.3
  - python >=3.7,<3.11
  - sra-tools >=3.0.1
  - wget
  - pip:
    - requests
    - rich
    - rich-click
    - executor
    - pysradb
